In [2]:
from random import uniform
import numpy as np

In [41]:
uniform(0.1, 3)
a = np.array([[1,2]])
np.append(a, [[2,3]], axis=0)

array([[1, 2],
       [2, 3]])

In [197]:
def uniform_non_one(ll, ul):
    u = uniform(ll, ul)
    while u > 0.95 and u < 1.1:
        u = uniform(ll, ul)
    return u

In [198]:
ll = 0.01
ul = 10

In [199]:
h1 = [0.10952162742614746, 0.09375166893005371, 0.0779874324798584, 0.07814216613769531, 0.09392857551574707, 0.1404414176940918, 0.15604043006896973, 0.12520694732666016, 0.14071965217590332, 0.1562652587890625]
l1 = [0.1407768726348877, 0.12499690055847168, 0.2656252384185791, 0.15607142448425293, 0.21893310546875, 0.26563048362731934, 0.37479186058044434, 0.1718769073486328, 0.29706287384033203]
t1 = np.array(h1 + l1)

h2 = [0.09376049041748047, 0.10939216613769531, 0.07812929153442383, 0.07813334465026855, 0.07811594009399414, 0.09353971481323242, 0.12479043006896973, 0.14062142372131348, 0.09375882148742676, 0.12502169609069824]
l2 = [0.14060688018798828, 0.10939216613769531, 0.25000476837158203, 0.15605878829956055, 0.15642929077148438, 0.2968902587890625, 0.3435804843902588, 0.2032921314239502, 0.21855950355529785]
t2 = np.array(h2 + l2)

h3 = [0.09388041496276855, 0.06250262260437012, 0.09393525123596191, 0.09393477439880371, 0.09373164176940918, 0.10936474800109863, 0.1248178482055664, 0.1562347412109375, 0.12506532669067383, 0.12498259544372559]
l3 = [0.15639424324035645, 0.20294523239135742, 0.24999070167541504, 0.1564328670501709, 0.18751168251037598, 0.23438000679016113, 0.3281230926513672, 0.21854138374328613, 0.21894097328186035]
t3 = np.array(h3 + l3)

In [233]:
def get_train_x():
    train_x = np.array([t1, t1*uniform_non_one(ll, ul), t2, t2*uniform_non_one(ll, ul), t3, t3*uniform_non_one(ll, ul)])
    return train_x

train_y = np.array([[1,0], [0,1], [1,0], [0,1], [1,0], [0,1]])
train_y = np.array([1, 0, 1, 0, 1, 0])

print(get_train_x())

[[0.10952163 0.09375167 0.07798743 0.07814217 0.09392858 0.14044142
  0.15604043 0.12520695 0.14071965 0.15626526 0.14077687 0.1249969
  0.26562524 0.15607142 0.21893311 0.26563048 0.37479186 0.17187691
  0.29706287]
 [0.49573157 0.42435145 0.35299724 0.35369762 0.42515219 0.63568489
  0.70629125 0.56672858 0.63694428 0.7073089  0.63720328 0.56577784
  1.20230879 0.70643154 0.99096456 1.20233254 1.69643349 0.77797245
  1.34460606]
 [0.09376049 0.10939217 0.07812929 0.07813334 0.07811594 0.09353971
  0.12479043 0.14062142 0.09375882 0.1250217  0.14060688 0.10939217
  0.25000477 0.15605879 0.15642929 0.29689026 0.34358048 0.20329213
  0.2185595 ]
 [0.27617646 0.32222038 0.23013394 0.23014588 0.23009461 0.27552615
  0.36757678 0.4142078  0.27617154 0.36825798 0.41416496 0.32222038
  0.7364022  0.45967937 0.46077071 0.87450588 1.01203439 0.59880767
  0.64377852]
 [0.09388041 0.06250262 0.09393525 0.09393477 0.09373164 0.10936475
  0.12481785 0.15623474 0.12506533 0.1249826  0.15639424 0.20

In [235]:
test_set = []

ht = [0.09595656394958496, 0.10863757133483887, 0.08635425567626953, 0.08549213409423828, 0.11526846885681152, 0.10271239280700684, 0.10387396812438965, 0.10887861251831055, 0.09198403358459473, 0.08949899673461914]
lt = [0.2758150100708008, 0.16951656341552734, 0.2143082618713379, 0.15245604515075684, 0.2742025852203369, 0.09780335426330566, 0.21977734565734863, 0.2144627571105957, 0.21666669845581055]
test_set = test_set + [ht+lt]
# Rohan yahoo 2
ht = [0.09210896492004395, 0.08857250213623047, 0.07890462875366211, 0.07576394081115723, 0.08545804023742676, 0.08250117301940918, 0.08504319190979004, 0.08667182922363281, 0.09841609001159668, 0.09374594688415527]
lt = [0.4260540008544922, 0.5018136501312256, 0.17831897735595703, 0.1512904167175293, 0.20851540565490723, 0.10800814628601074, 0.19591522216796875, 0.1971726417541504, 0.19782376289367676]
test_set = test_set + [ht+lt]

ht = [0.07265639305114746, 0.07063674926757812, 0.07595586776733398, 0.07819533348083496, 0.07197856903076172, 0.08706784248352051, 0.13755583763122559, 0.0965118408203125, 0.09829139709472656, 0.0923457145690918]
lt = [1.4470746517181396, 1.1023054122924805, 0.9270460605621338, 0.3101646900177002, 1.2914505004882812, 0.16473960876464844, 0.9366493225097656, 0.3097951412200928, 0.24070501327514648]
test_set = test_set + [ht+lt]

ht = [0.0, 0.10958433151245117, 0.07809805870056152, 0.07813620567321777, 0.09373617172241211, 0.09377050399780273, 0.1093902587890625, 0.12500691413879395, 0.1562497615814209, 0.10938119888305664]
lt = [0.0937190055847168, 0.15646839141845703, 0.32811784744262695, 0.15625548362731934, 0.7656264305114746, 0.3437337875366211, 0.7187540531158447, 0.2343895435333252, 0.29685139656066895]
test_set = test_set + [ht+lt]

test_set = np.array(test_set)
test_y_set = np.array([[0, 1], [0, 1], [0, 1], [0, 1]])
test_y_set = np.array([0,0, 0, 0])

In [202]:
input_len = len(t1)

In [7]:
from keras.models import Sequential
from keras.layers import Dense
from keras.callbacks import EarlyStopping

Using TensorFlow backend.


In [271]:
model = Sequential()
# model.add(Dense(int((input_len+2)/2), input_shape=(input_len,)))
model.add(Dense(int((input_len+2)*2), input_shape=(input_len,)))
model.add(Dense(int((input_len+2)*4)))
model.add(Dense(int((input_len+2)*4)))
model.add(Dense(int((input_len+2)*2)))
model.add(Dense(1, activation="sigmoid"))

In [272]:
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['mse'])

In [339]:
for i in range(1, 2):
    model.fit(get_train_x(), train_y, 
              validation_data=(test_set, test_y_set), 
              epochs=50,
#               callbacks=[EarlyStopping(patience=20, restore_best_weights=True)], 
              batch_size=1)

Train on 6 samples, validate on 4 samples
Epoch 1/50
6/6 [==============================] - 0s 4ms/step - loss: 2.6901 - mean_squared_error: 0.4597 - val_loss: 0.3248 - val_mean_squared_error: 0.1058
Epoch 2/50
6/6 [==============================] - 0s 6ms/step - loss: 0.9922 - mean_squared_error: 0.3848 - val_loss: 0.2528 - val_mean_squared_error: 0.0688
Epoch 3/50
6/6 [==============================] - 0s 5ms/step - loss: 0.7964 - mean_squared_error: 0.3002 - val_loss: 0.4608 - val_mean_squared_error: 0.1590
Epoch 4/50
6/6 [==============================] - 0s 7ms/step - loss: 0.7890 - mean_squared_error: 0.2958 - val_loss: 0.6139 - val_mean_squared_error: 0.2294
Epoch 5/50
6/6 [==============================] - 0s 6ms/step - loss: 0.8461 - mean_squared_error: 0.3252 - val_loss: 0.3506 - val_mean_squared_error: 0.1076
Epoch 6/50
6/6 [==============================] - 0s 5ms/step - loss: 0.7530 - mean_squared_error: 0.2798 - val_loss: 0.4345 - val_mean_squared_error: 0.1452
Epoch 7/50

In [340]:
# Akshay left
# ht = [0.15553021430969238, 0.1833341121673584, 0.1120145320892334, 0.11858105659484863, 0.1272571086883545]
# lt = [0.20326781272888184, 0.3910393714904785, 0.16507315635681152, 0.24552321434020996]

# Rohan 1
# ht = [0.13084912300109863, 0.08150935173034668, 0.08852767944335938, 0.0871877670288086, 0.12709331512451172]
# lt = [0.19961810111999512, 0.2398664951324463, 0.1501936912536621, 0.19040274620056152]

# Rohan 2
# ht = [0.11770796775817871, 0.11753606796264648, 0.06077170372009277, 0.06744670867919922, 0.12628793716430664]
# lt = [0.1910703182220459, 0.18630051612854004, 0.14431166648864746, 0.13070464134216309]

# Rohan laptop 1

# ht = [0.10936403274536133, 0.07821130752563477, 0.06249117851257324, 0.09370899200439453, 0.10935616493225098]
# lt = [0.12534356117248535, 0.17193865776062012, 0.1405942440032959, 0.1562049388885498]

# Rohan laptop 2

# ht = [0.09372639656066895, 0.07808184623718262, 0.06249213218688965, 0.07810783386230469, 0.0780951976776123]
# lt = [0.15621066093444824, 0.1718285083770752, 0.12497735023498535, 0.17184019088745117]

# Rohan yahoo
ht = [0.09595656394958496, 0.10863757133483887, 0.08635425567626953, 0.08549213409423828, 0.11526846885681152, 0.10271239280700684, 0.10387396812438965, 0.10887861251831055, 0.09198403358459473, 0.08949899673461914]
lt = [0.2758150100708008, 0.16951656341552734, 0.2143082618713379, 0.15245604515075684, 0.2742025852203369, 0.09780335426330566, 0.21977734565734863, 0.2144627571105957, 0.21666669845581055]

# Rohan yahoo 2
# ht = [0.09210896492004395, 0.08857250213623047, 0.07890462875366211, 0.07576394081115723, 0.08545804023742676, 0.08250117301940918, 0.08504319190979004, 0.08667182922363281, 0.09841609001159668, 0.09374594688415527]
# lt = [0.4260540008544922, 0.5018136501312256, 0.17831897735595703, 0.1512904167175293, 0.20851540565490723, 0.10800814628601074, 0.19591522216796875, 0.1971726417541504, 0.19782376289367676]

# ht = [0.07265639305114746, 0.07063674926757812, 0.07595586776733398, 0.07819533348083496, 0.07197856903076172, 0.08706784248352051, 0.13755583763122559, 0.0965118408203125, 0.09829139709472656, 0.0923457145690918]
# lt = [1.4470746517181396, 1.1023054122924805, 0.9270460605621338, 0.3101646900177002, 1.2914505004882812, 0.16473960876464844, 0.9366493225097656, 0.3097951412200928, 0.24070501327514648]

# ht = [0.0, 0.10958433151245117, 0.07809805870056152, 0.07813620567321777, 0.09373617172241211, 0.09377050399780273, 0.1093902587890625, 0.12500691413879395, 0.1562497615814209, 0.10938119888305664]
# lt = [0.0937190055847168, 0.15646839141845703, 0.32811784744262695, 0.15625548362731934, 0.7656264305114746, 0.3437337875366211, 0.7187540531158447, 0.2343895435333252, 0.29685139656066895]

model.predict(np.array([ht+lt]))

array([[0.5316663]], dtype=float32)

In [341]:
# Akshay 1
# hs = [0.10079240798950195, 0.0859220027923584, 0.1017765998840332, 0.10221600532531738, 0.09874200820922852]
# ls = [0.17093300819396973, 0.17932987213134766, 0.16470694541931152, 0.19497990608215332]
# Akshay 2
# hs = [0.09600543975830078, 0.09759974479675293, 0.09690403938293457, 0.09656500816345215, 0.09008073806762695]
# ls = [0.13527464866638184, 0.18556714057922363, 0.17046308517456055, 0.17670679092407227]
# Akshay yahoo
# hs = [0.09196853637695312, 0.011778831481933594, 0.0840301513671875, 0.0810387134552002, 0.08589315414428711, 0.11729216575622559, 0.12870311737060547, 0.14802074432373047, 0.12166929244995117, 0.11128926277160645]
# ls = [0.149031400680542, 0.10028648376464844, 0.2565755844116211, 0.1504380702972412, 0.15475082397460938, 0.2694101333618164, 0.3309817314147949, 0.16613292694091797, 0.23165583610534668]
# AKshay yahoo 2
hs = [0.08472108840942383, 0.10623908042907715, 0.08556842803955078, 0.07705402374267578, 0.07933664321899414, 0.11913442611694336, 0.13387012481689453, 0.13739967346191406, 0.11761331558227539, 0.12718510627746582]
ls = [0.1788322925567627, 0.1804337501525879, 0.22486472129821777, 0.14758682250976562, 0.16390132904052734, 0.23365473747253418, 0.3056659698486328, 0.15131092071533203, 0.21889853477478027]

# hs = [0.11050009727478027, 0.013557195663452148, 0.07181286811828613, 0.08824348449707031, 0.09769868850708008, 0.10928177833557129, 0.12917757034301758, 0.15904521942138672, 0.10855269432067871, 0.14252805709838867]
# ls = [0.14574408531188965, 0.09774065017700195, 0.2709169387817383, 0.14959049224853516, 0.15134310722351074, 0.2423112392425537, 0.25729918479919434, 0.165238618850708, 0.21039104461669922]

# hs = [0.09374141693115234, 0.031228065490722656, 0.09374380111694336, 0.07792496681213379, 0.0781397819519043, 0.10932469367980957, 0.12498092651367188, 0.12499880790710449, 0.10937356948852539, 0.09372949600219727]
# ls = [0.12480902671813965, 0.09394240379333496, 0.26561760902404785, 0.14061284065246582, 0.17188310623168945, 0.2811088562011719, 0.2657663822174072, 0.15625977516174316, 0.20313167572021484]

model.predict(np.array([hs+ls]))

array([[0.5237252]], dtype=float32)