In [1]:
from random import uniform, randint
from math import floor, ceil
import numpy as np

import tensorflow as tf
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam, RMSprop
from keras.callbacks import EarlyStopping, TensorBoard

Using TensorFlow backend.


In [2]:
ll = 0.0001
ul = 3
sample_x = []
global fc_model
global graph
graph = tf.get_default_graph()

In [25]:
def uniform_non_one(ll, ul):
    u = uniform(ll, ul)
    while u > 0.95 and u < 1.1:
        u = uniform(ll, ul)
    return u

def get_fakes(fakes):
    global ll, ul
    return np.sort(
        np.append(
            np.linspace(0,1, floor(fakes/2), endpoint=False), 
            np.linspace(3,1, ceil(fakes/2), endpoint=False) 
        ))
    
def get_train_data():
    global sample_x, ll, ul
    fakes = len(sample_x) + 2
    train_x = np.array(sample_x)
    train_y = np.ones(len(sample_x))
    fake_samples = get_fakes(fakes)
    
    for i in range(0, fakes):
        train_x = np.append(train_x, [train_x[randint(0, len(sample_x)-1)] * fake_samples[i]], axis=0)
        train_y = np.append(train_y, [0])
        
    return (train_x, train_y)
    
def get_model():
    input_len = len(sample_x[0])

    model = Sequential()
    # model.add(Dense(int((input_len+2)/2), input_shape=(input_len,)))
    model.add(Dense(int((input_len+2)*2), input_shape=(input_len,)))
    model.add(Dense(int((input_len+2)*4), activation="tanh"))
    model.add(Dense(1, activation="sigmoid"))
    model.summary()
    
    model.compile(optimizer=Adam(2e-4),
              loss='binary_crossentropy',
              metrics=['mse'])
    
    return model

In [20]:
def train():
	global fc_model
	fc_model = get_model()
	x, y = get_train_data()
	print(fc_model.evaluate(np.array([[99, 357, 117, 99, 95, 83, 131, 119, 87, 110, 361, 185, 298, 261, 160, 193, 175, 169, 208, 215]]), np.array([1])))
	fc_model.fit(x, y, 
			  validation_split= 0.0, 
			  epochs=500,
			   callbacks=[ TensorBoard(),
                   EarlyStopping('loss', patience=50, restore_best_weights=True)
               ], 
			  batch_size=32)
	return 'trained'

def predict(test_x):
	prediction = fc_model.predict(test_x)
	print(prediction)
	return 'Prediction: ' + prediction

In [5]:
sample_x = [[293, 93, 101, 98, 105, 74, 129, 112, 108, 298, 119, 174, 252, 163, 157, 201, 163, 190, 196, 226], 
            [308, 87, 98, 96, 91, 81, 126, 96, 109, 290, 118, 200, 250, 197, 165, 186, 179, 201, 181, 225], 
            [359, 87, 101, 86, 106, 86, 156, 121, 101, 499, 141, 245, 266, 215, 142, 204, 157, 192, 206, 241]]

In [26]:
train()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_10 (Dense)             (None, 44)                924       
_________________________________________________________________
dense_11 (Dense)             (None, 88)                3960      
_________________________________________________________________
dense_12 (Dense)             (None, 1)                 89        
Total params: 4,973
Trainable params: 4,973
Non-trainable params: 0
_________________________________________________________________
1/1 [==============================] - 0s 401ms/step
[0.46977370977401733, 0.1405172348022461]
Epoch 1/500
8/8 [==============================] - 1s 66ms/step - loss: 1.2374 - mean_squared_error: 0.4264
Epoch 2/500
8/8 [==============================] - 0s 375us/step - loss: 1.0622 - mean_squared_error: 0.3830
Epoch 3/500
8/8 [==============================] - 0s 750us/step - loss: 1.0271 - mean_squar

Epoch 69/500
8/8 [==============================] - 0s 1ms/step - loss: 0.6199 - mean_squared_error: 0.2156
Epoch 70/500
8/8 [==============================] - 0s 70us/step - loss: 0.6190 - mean_squared_error: 0.2150
Epoch 71/500
8/8 [==============================] - 0s 4ms/step - loss: 0.6177 - mean_squared_error: 0.2143
Epoch 72/500
8/8 [==============================] - 0s 371us/step - loss: 0.6157 - mean_squared_error: 0.2134
Epoch 73/500
8/8 [==============================] - 0s 1ms/step - loss: 0.6140 - mean_squared_error: 0.2125
Epoch 74/500
8/8 [==============================] - 0s 415us/step - loss: 0.6125 - mean_squared_error: 0.2118
Epoch 75/500
8/8 [==============================] - 0s 1ms/step - loss: 0.6110 - mean_squared_error: 0.2111
Epoch 76/500
8/8 [==============================] - 0s 2ms/step - loss: 0.6096 - mean_squared_error: 0.2104
Epoch 77/500
8/8 [==============================] - 0s 253us/step - loss: 0.6087 - mean_squared_error: 0.2099
Epoch 78/500
8/8 [===

Epoch 144/500
8/8 [==============================] - 0s 318us/step - loss: 0.5500 - mean_squared_error: 0.1830
Epoch 145/500
8/8 [==============================] - 0s 332us/step - loss: 0.5500 - mean_squared_error: 0.1830
Epoch 146/500
8/8 [==============================] - 0s 413us/step - loss: 0.5495 - mean_squared_error: 0.1828
Epoch 147/500
8/8 [==============================] - 0s 2ms/step - loss: 0.5487 - mean_squared_error: 0.1824
Epoch 148/500
8/8 [==============================] - 0s 498us/step - loss: 0.5497 - mean_squared_error: 0.1830
Epoch 149/500
8/8 [==============================] - 0s 251us/step - loss: 0.5487 - mean_squared_error: 0.1825
Epoch 150/500
8/8 [==============================] - 0s 375us/step - loss: 0.5487 - mean_squared_error: 0.1825
Epoch 151/500
8/8 [==============================] - 0s 358us/step - loss: 0.5484 - mean_squared_error: 0.1824
Epoch 152/500
8/8 [==============================] - 0s 196us/step - loss: 0.5481 - mean_squared_error: 0.1823
Epo

Epoch 219/500
8/8 [==============================] - 0s 867us/step - loss: 0.5286 - mean_squared_error: 0.1761
Epoch 220/500
8/8 [==============================] - 0s 676us/step - loss: 0.5277 - mean_squared_error: 0.1757
Epoch 221/500
8/8 [==============================] - 0s 1ms/step - loss: 0.5272 - mean_squared_error: 0.1755
Epoch 222/500
8/8 [==============================] - 0s 1ms/step - loss: 0.5270 - mean_squared_error: 0.1754
Epoch 223/500
8/8 [==============================] - 0s 875us/step - loss: 0.5268 - mean_squared_error: 0.1754
Epoch 224/500
8/8 [==============================] - 0s 500us/step - loss: 0.5266 - mean_squared_error: 0.1753
Epoch 225/500
8/8 [==============================] - 0s 633us/step - loss: 0.5264 - mean_squared_error: 0.1752
Epoch 226/500
8/8 [==============================] - 0s 623us/step - loss: 0.5260 - mean_squared_error: 0.1750
Epoch 227/500
8/8 [==============================] - 0s 2ms/step - loss: 0.5256 - mean_squared_error: 0.1749
Epoch 2

Epoch 294/500
8/8 [==============================] - 0s 2ms/step - loss: 0.5140 - mean_squared_error: 0.1718
Epoch 295/500
8/8 [==============================] - 0s 476us/step - loss: 0.5138 - mean_squared_error: 0.1717
Epoch 296/500
8/8 [==============================] - 0s 251us/step - loss: 0.5137 - mean_squared_error: 0.1717
Epoch 297/500
8/8 [==============================] - 0s 474us/step - loss: 0.5135 - mean_squared_error: 0.1716
Epoch 298/500
8/8 [==============================] - 0s 1ms/step - loss: 0.5134 - mean_squared_error: 0.1716
Epoch 299/500
8/8 [==============================] - 0s 625us/step - loss: 0.5132 - mean_squared_error: 0.1715
Epoch 300/500
8/8 [==============================] - 0s 266us/step - loss: 0.5131 - mean_squared_error: 0.1715
Epoch 301/500
8/8 [==============================] - 0s 508us/step - loss: 0.5130 - mean_squared_error: 0.1715
Epoch 302/500
8/8 [==============================] - 0s 1ms/step - loss: 0.5128 - mean_squared_error: 0.1714
Epoch 3

Epoch 368/500
8/8 [==============================] - 0s 876us/step - loss: 0.5065 - mean_squared_error: 0.1700
Epoch 369/500
8/8 [==============================] - 0s 284us/step - loss: 0.5065 - mean_squared_error: 0.1700
Epoch 370/500
8/8 [==============================] - 0s 561us/step - loss: 0.5064 - mean_squared_error: 0.1700
Epoch 371/500
8/8 [==============================] - 0s 1ms/step - loss: 0.5064 - mean_squared_error: 0.1700
Epoch 372/500
8/8 [==============================] - 0s 1ms/step - loss: 0.5063 - mean_squared_error: 0.1700
Epoch 373/500
8/8 [==============================] - 0s 1ms/step - loss: 0.5062 - mean_squared_error: 0.1700
Epoch 374/500
8/8 [==============================] - 0s 412us/step - loss: 0.5061 - mean_squared_error: 0.1699
Epoch 375/500
8/8 [==============================] - 0s 251us/step - loss: 0.5060 - mean_squared_error: 0.1699
Epoch 376/500
8/8 [==============================] - 0s 517us/step - loss: 0.5060 - mean_squared_error: 0.1699
Epoch 3

Epoch 443/500
8/8 [==============================] - 0s 625us/step - loss: 0.5016 - mean_squared_error: 0.1691
Epoch 444/500
8/8 [==============================] - 0s 2ms/step - loss: 0.5016 - mean_squared_error: 0.1690
Epoch 445/500
8/8 [==============================] - 0s 621us/step - loss: 0.5015 - mean_squared_error: 0.1690
Epoch 446/500
8/8 [==============================] - 0s 2ms/step - loss: 0.5015 - mean_squared_error: 0.1690
Epoch 447/500
8/8 [==============================] - 0s 2ms/step - loss: 0.5014 - mean_squared_error: 0.1690
Epoch 448/500
8/8 [==============================] - 0s 407us/step - loss: 0.5014 - mean_squared_error: 0.1690
Epoch 449/500
8/8 [==============================] - 0s 375us/step - loss: 0.5013 - mean_squared_error: 0.1690
Epoch 450/500
8/8 [==============================] - 0s 433us/step - loss: 0.5012 - mean_squared_error: 0.1690
Epoch 451/500
8/8 [==============================] - 0s 985us/step - loss: 0.5012 - mean_squared_error: 0.1690
Epoch 4

'trained'

In [27]:
fc_model.predict(np.array([[304,78,104,115,97,94,162,130,117,358,130,191,229,151,170,186,196,183,209,224]]))

array([[0.5706173]], dtype=float32)

In [28]:
fc_model.predict([sample_x])

array([[0.35207328],
       [0.85886186],
       [0.36334887]], dtype=float32)

In [488]:
from scipy.stats import truncnorm
from math import floor, ceil

def get_truncated_normal(mean=0, sd=1, low=0, upp=10):
    return truncnorm(
        (low - mean) / sd, (upp - mean) / sd, loc=mean, scale=sd)
#get_truncated_normal(mean=1, upp=3).rvs(size=4)
fakes=6
np.sort(np.append(np.linspace(0,1, floor(fakes/2), endpoint=False), np.linspace(3,1, ceil(fakes/2), endpoint=False) ))

array([0.        , 0.33333333, 0.66666667, 1.66666667, 2.33333333,
       3.        ])

In [46]:
np_x = np.array(sample_x)
#np.abs(np_x[2] - np_x[1]).max()
np.mean(sample_x, axis=0)

array([320.        ,  89.        , 100.        ,  93.33333333,
       100.66666667,  80.33333333, 137.        , 109.66666667,
       106.        , 362.33333333, 126.        , 206.33333333,
       256.        , 191.66666667, 154.66666667, 197.        ,
       166.33333333, 194.33333333, 194.33333333, 230.66666667])